# Generated by Django 5.1.2 on 2024-10-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0002_imagetask_celery_task_id_imagetask_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetask',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
