# Generated by Django 5.1.2 on 2024-10-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_imagetask_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetask',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
