# Generated by Django 5.1.2 on 2024-10-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0004_imagetask_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetask',
            name='original_image_compressed',
            field=models.ImageField(blank=True, null=True, upload_to='original_images/compressed'),
        ),
    ]
